version: '3.8'

services:
  nodeapp:
    container_name: nodeapp
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_PORT: ${APP_PORT}
    ports:
      - 80:8081